# Generated by Django 5.1.2 on 2024-12-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_listing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Dezaprobat'), (1, 'Activ'), (2, 'Așteptare')], db_index=True, default=2)),
                ('meta_title', models.CharField(blank=True, max_length=90)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='listings', to='api.tag'),
        ),
    ]
