# Generated by Django 5.1.2 on 2024-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usertype_remove_user_user_type_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_active_field',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
