# Generated by Django 5.1.2 on 2024-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersubscription_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
