# Generated by Django 5.1.2 on 2024-11-07 01:46

import django.db.models.deletion
import django_resized.forms
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('meta_title', models.CharField(blank=True, max_length=90)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('custom_text', models.TextField(blank=True, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[160, 160], upload_to='category_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='api.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
