# Generated by Django 5.1.2 on 2024-12-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tags',
            new_name='tag',
        ),
    ]
