# Generated by Django 5.1.2 on 2024-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tags_listing_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_good_deal',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_manual_label',
            field=models.BooleanField(default=False),
        ),
    ]
