# Generated by Django 5.1.2 on 2024-12-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_listing_is_good_deal_listing_is_manual_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='compartimentare',
            field=models.CharField(blank=True, choices=[(0, 'Decomandat'), (1, 'Semidecomandat'), (2, 'Nedecomandat'), (3, 'Circular')], max_length=20, null=True),
        ),
    ]
