# Generated by Django 5.1.2 on 2024-12-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_listing_compartimentare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='compartimentare',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Decomandat'), (1, 'Semidecomandat'), (2, 'Nedecomandat'), (3, 'Circular')], db_index=True, null=True),
        ),
    ]
