# Generated by Django 5.1.2 on 2024-12-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_listing_compartimentare'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Apartamente'), (1, 'Birouri și Spații Comerciale'), (2, 'Case și Vile'), (3, 'Terenuri'), (4, 'Alte proprietăți')], db_index=True, null=True),
        ),
    ]
