# Generated by Django 5.1.2 on 2024-12-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='zonare',
            field=models.CharField(blank=True, choices=[('intravilan', 'Intravilan'), ('extravilan', 'Extravilan')], help_text='Zonarea poate fi intravilan, extravilan sau necompletată.', max_length=15, null=True),
        ),
    ]
