# Generated by Django 5.1.2 on 2024-12-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_listing_zonare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='zonare',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'intravilan'), (1, 'extravilan')], db_index=True, help_text='Zonarea poate fi intravilan, extravilan sau necompletată.', null=True),
        ),
    ]
