# Generated by Django 5.1.2 on 2024-12-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_companyprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='account_type',
        ),
    ]
