# Generated by Django 5.1.2 on 2024-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_listing_zonare'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='suprafata_utila',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Suprafață utilă'),
        ),
    ]
