# Generated by Django 5.1.2 on 2024-12-06 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_user_type_user_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strada', models.CharField(max_length=255)),
                ('strada_numar', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Numărul străzii trebuie să fie un număr.')])),
                ('oras', models.CharField(max_length=255)),
                ('judet', models.CharField(max_length=255)),
                ('cod_postal', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Codul poștal trebuie să fie format din 6 cifre.')])),
                ('tara', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
