# Generated by Django 5.1.2 on 2024-12-07 07:15

import django.db.models.deletion
import django_bleach.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', django_bleach.models.BleachField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.SmallIntegerField(choices=[(0, 'Lei'), (1, 'EUR')], default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (3, 'Rejected')], db_index=True, default=0)),
                ('photo1', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('photo2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('photo3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('photo4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('photo5', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('photo6', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('photo7', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('photo8', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('photo9', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='listings')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('views_count', models.BigIntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=140)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_listings', to='api.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_listings', to='api.city')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_listings', to='api.county')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhood_listings', to='api.neighborhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_date'],
            },
        ),
    ]
