# Generated by Django 5.1.2 on 2024-12-18 08:18

import django.db.models.deletion
import django_bleach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=django_bleach.models.BleachField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='api.listing'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='text',
            field=django_bleach.models.BleachField(),
        ),
    ]
