# Generated by Django 5.1.2 on 2024-12-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_report_reason_alter_suggestion_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
