# Generated by Django 5.1.2 on 2024-12-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_managementcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='numar_camere',
            field=models.IntegerField(blank=True, choices=[(1, '1 Cameră'), (2, '2 Camere'), (3, '3 Camere'), (4, '4 Camere'), (5, '5+ Camere')], db_index=True, default=1, help_text='Se aplica doar pentru apartamente, case, vile, spatii comerciale.', null=True),
        ),
    ]
