# Generated by Django 5.1.2 on 2024-12-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_listing_photo1_hash_listing_photo2_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='year_of_construction',
            field=models.IntegerField(blank=True, help_text='Year of construction', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'Lei'), (1, 'EUR')], default=1),
        ),
    ]
