# Generated by Django 5.1.2 on 2024-12-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_listing_year_of_construction_alter_listing_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Dezvoltator / Constructor'), (1, 'Agenție Imobiliară'), (2, 'Broker Ipotecar'), (3, 'Instituție Financiară'), (4, 'Alt Tip')], help_text='Tipul companiei. Poate fi lăsat necompletat.', null=True),
        ),
    ]
