# Generated by Django 5.1.2 on 2024-12-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_companyprofile_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Compania la care este asociat acest agent imobiliar (opțional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='api.companyprofile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('person', 'Persoană Fizică'), ('company', 'Companie'), ('agent', 'Agent Imobiliar')], default='person', max_length=10),
        ),
    ]
