# Generated by Django 5.1.2 on 2024-12-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_claimrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Indică dacă utilizatorul a fost validat ca fiind proprietar al anunțului.'),
        ),
    ]
