# Generated by Django 5.1.2 on 2024-12-24 18:56

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_listing_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[400, 200], upload_to='company_logos'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[300, 300], upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
