# Generated by Django 5.1.2 on 2024-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_user_slug_user_username_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
