# Generated by Django 5.1.2 on 2024-12-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_listing_is_active_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=40745111111, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
