# Generated by Django 5.1.2 on 2024-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='structura',
            field=models.IntegerField(blank=True, choices=[(0, 'Caramida'), (1, 'Beton'), (2, 'BCA'), (3, 'Placi'), (4, 'Lemn'), (5, 'Metal'), (6, 'Altele')], db_index=True, null=True),
        ),
    ]
