# Generated by Django 5.1.2 on 2024-12-28 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_listing_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buyer_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Introduceți procentul comisionului pentru cumpărător (maxim 50%).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Demisol'), (1, 'Parter'), (2, 'Etaj 1'), (3, 'Etaj 2'), (4, 'Etaj 3'), (5, 'Etaj 4'), (6, 'Etaj 5'), (7, 'Etaj 6'), (8, 'Etaj 7'), (9, 'Etaj 8'), (10, 'Etaj 9'), (11, 'Etaj 10'), (12, 'Etaj 11'), (13, 'Etaj 12'), (14, 'Etaj 13'), (15, 'Etaj 14'), (16, 'Etaj 15'), (17, 'Etaj 16'), (18, 'Etaj 17'), (19, 'Etaj 18'), (20, 'Etaj 19'), (21, 'Etaj 20'), (22, 'Mansarda'), (23, 'Ultimele 2 etaje')], db_index=True, null=True),
        ),
    ]
