# Generated by Django 5.1.2 on 2024-12-28 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_listing_buyer_commission_alter_listing_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buyer_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Introduceți procentul comisionului pentru cumpărător (maxim 50%).', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
    ]
