# Generated by Django 5.1.2 on 2024-12-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_imagehash_remove_listing_photo1_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehash',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_hashes', to='api.listing'),
        ),
        migrations.AddField(
            model_name='imagehash',
            name='photo_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
