# Generated by Django 5.1.2 on 2024-12-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_imagehash_listing_imagehash_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehash',
            name='listing',
        ),
        migrations.AddField(
            model_name='imagehash',
            name='listing_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
