# Generated by Django 5.1.2 on 2024-12-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_imagehash_listing_imagehash_listing_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehash',
            name='photo_name',
        ),
    ]
