# Generated by Django 5.1.2 on 2024-12-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_imagehash_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehash',
            name='photo_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
