# Generated by Django 5.1.2 on 2025-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_listingactivitylog_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehash',
            name='photo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='compartimentare',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'decomandat'), (1, 'semidecomandat'), (2, 'nedecomandat'), (3, 'circular')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'demisol'), (1, 'parter'), (2, 'etaj 1'), (3, 'etaj 2'), (4, 'etaj 3'), (5, 'etaj 4'), (6, 'etaj 5'), (7, 'etaj 6'), (8, 'etaj 7'), (9, 'etaj 8'), (10, 'etaj 9'), (11, 'etaj 10'), (12, 'etaj 11'), (13, 'etaj 12'), (14, 'etaj 13'), (15, 'etaj 14'), (16, 'etaj 15'), (17, 'etaj 16'), (18, 'etaj 17'), (19, 'etaj 18'), (20, 'etaj 19'), (21, 'etaj 20'), (22, 'ultimul etaj'), (23, 'mansarda')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='structura',
            field=models.IntegerField(blank=True, choices=[(0, 'caramida'), (1, 'beton'), (2, 'BCA'), (3, 'placi'), (4, 'lemn'), (5, 'metal'), (6, 'altele')], db_index=True, null=True),
        ),
    ]
