# Generated by Django 5.1.2 on 2025-01-10 17:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_imagehash_photo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buyer_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Introduceți procentul comisionului pentru cumpărător (maxim 50%).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))]),
        ),
    ]
