# Generated by Django 5.1.2 on 2025-01-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_listing_buyer_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Indică dacă anunțul este promovat.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='valability_promote_date',
            field=models.DateField(blank=True, help_text='Data până la care anunțul este promovat.', null=True),
        ),
    ]
