# Generated by Django 5.1.2 on 2025-02-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionhistory',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.payment'),
        ),
    ]
