# Generated by Django 5.1.2 on 2025-02-14 13:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_privacypolicysection_privacypolicyhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicyhistory',
            name='old_content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='privacypolicysection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
