# Generated by Django 5.1.2 on 2025-02-15 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_privacypolicyhistory_old_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicyhistory',
            name='diff_content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicyhistory',
            name='diff_title',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
