# Generated by Django 5.1.2 on 2025-02-15 15:33

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_privacypolicyhistory_diff_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicyhistory',
            name='current_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicyhistory',
            name='current_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
