# Generated by Django 5.1.2 on 2025-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_termspolicysection_termspolicyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='number_of_bathrooms',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Fără baie'), (1, '1 baie'), (2, '2 băi'), (3, '3 sau mai multe băi')], db_index=True, null=True),
        ),
    ]
