# Generated by Django 5.1.2 on 2025-02-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_listing_number_of_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='foundation_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Parter'), (1, 'Subsol + Parter'), (2, 'Demisol + Parter')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_attic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_floors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='numar_camere',
            field=models.IntegerField(blank=True, choices=[(1, '1 cameră'), (2, '2 camere'), (3, '3 camere'), (4, '4 camere'), (5, '5+ camere')], db_index=True, default=1, help_text='Se aplica doar pentru apartamente, case, vile, spatii comerciale.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='number_of_bathrooms',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Fără baie'), (1, '1 baie'), (2, '2 băi'), (3, '3 sau mai multe băi')], db_index=True, help_text='Se aplica doar pentru apartamente, case, vile, spatii comerciale, pensiuni și hoteluri.', null=True),
        ),
    ]
