# Generated by Django 5.1.2 on 2025-02-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_listing_compartimentare_alter_listing_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
