# Generated by Django 5.1.2 on 2025-02-27 02:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_listing_compartimentare_alter_listing_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auto_renewal',
            field=models.BooleanField(default=False, help_text='Dacă este activ, anunțul se va prelungi automat la expirare.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='structura',
            field=models.IntegerField(choices=[(0, 'Cărămidă'), (1, 'Beton'), (2, 'BCA'), (3, 'Plăci'), (4, 'Lemn'), (5, 'Metal'), (6, 'Cărămidă + BCA'), (7, 'Beton + Metal'), (8, 'Lemn + Metal'), (9, 'Zidărie mixtă (Cărămidă + BCA + Beton)'), (10, 'Structură ușoară (Metal + Lemn + Plăci)'), (11, 'Combinată (Mai multe materiale)')], db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='valability_end_date',
            field=models.DateField(default=api.models.default_expiry_date, help_text='Data până la care anunțul este valid. Implicit: 90 de zile.'),
        ),
    ]
