# Generated by Django 5.1.2 on 2025-02-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_listing_auto_renewal_alter_listing_structura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='notified_on_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
