# Generated by Django 5.1.2 on 2025-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_listing_notified_on_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='numar_camere',
            field=models.IntegerField(choices=[(1, '1 cameră'), (2, '2 camere'), (3, '3 camere'), (4, '4 camere'), (5, '5+ camere')], db_index=True, help_text='Se aplica doar pentru apartamente, case, vile, spatii comerciale.'),
        ),
    ]
