# Generated by Django 5.1.2 on 2025-02-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_listing_numar_camere_alter_listing_zonare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Apartamente'), (1, 'Birouri și Spații Comerciale'), (2, 'Case și Vile'), (3, 'Terenuri'), (4, 'Alte proprietăți'), (5, 'Pensiuni și hoteluri')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_of_construction',
            field=models.IntegerField(blank=True, help_text='Year of construction', null=True),
        ),
    ]
