# Generated by Django 5.1.2 on 2025-02-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_listing_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='suprafata_constructie',
            field=models.FloatField(blank=True, null=True, verbose_name='Suprafață construită'),
        ),
        migrations.AddField(
            model_name='listing',
            name='suprafata_terenului',
            field=models.FloatField(blank=True, null=True, verbose_name='Suprafață terenului'),
        ),
    ]
