# Generated by Django 5.1.2 on 2025-02-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_listing_suprafata_constructie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='number_of_bedrooms',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1 dormitor'), (2, '2 dormitoare'), (3, '3 dormitoare'), (4, '4 dormitoare'), (5, '5+ dormitoare')], db_index=True, null=True),
        ),
    ]
