# Generated by Django 5.1.2 on 2025-03-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_listing_number_of_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='number_of_balconies',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Fără balcon'), (1, '1 balcon'), (2, '2 balcoane'), (3, '3 balcoane'), (4, '4+ balcoane')], db_index=True, null=True),
        ),
    ]
