# Generated by Django 5.1.2 on 2025-03-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_listing_suprafata_balcoane'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='numar_camere_maxim',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
