# Generated by Django 5.1.2 on 2025-03-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_category_numar_camere_maxim'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='clasa_energetica',
            field=models.IntegerField(blank=True, choices=[(0, 'A (Foarte bună)'), (1, 'B (Bună)'), (2, 'C (Medie)'), (3, 'D (Sub medie)'), (4, 'E (Scăzută)'), (5, 'F (Foarte scăzută)'), (6, 'G (Extrem de scăzută)')], db_index=True, null=True),
        ),
    ]
