# Generated by Django 5.1.2 on 2025-03-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_listing_clasa_energetica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='clasa_energetica',
            field=models.IntegerField(blank=True, choices=[(0, 'Necunoscută'), (1, 'A (Foarte bună)'), (2, 'B (Bună)'), (3, 'C (Medie)'), (4, 'D (Sub medie)'), (5, 'E (Scăzută)'), (6, 'F (Foarte scăzută)'), (7, 'G (Extrem de scăzută)')], db_index=True, null=True),
        ),
    ]
