MONTHS_RO = {
    "January": "ianuarie",
    "February": "februarie",
    "March": "martie",
    "April": "aprilie",
    "May": "mai",
    "June": "iunie",
    "July": "iulie",
    "August": "august",
    "September": "septembrie",
    "October": "octombrie",
    "November": "noiembrie",
    "December": "decembrie",
}

# Definim opțiunile pentru etaj
FLOOR_CHOICES = [
    (0, 'Demisol'),
    (1, 'Parter'),
    (2, 'Etaj 1'),
    (3, 'Etaj 2'),
    (4, 'Etaj 3'),
    (5, 'Etaj 4'),
    (6, 'Etaj 5'),
    (7, 'Etaj 6'),
    (8, 'Etaj 7'),
    (9, 'Etaj 8'),
    (10, 'Etaj 9'),
    (11, 'Etaj 10'),
    (12, 'Etaj 11'),
    (13, 'Etaj 12'),
    (14, 'Etaj 13'),
    (15, 'Etaj 14'),
    (16, 'Etaj 15'),
    (17, 'Etaj 16'),
    (18, 'Etaj 17'),
    (19, 'Etaj 18'),
    (20, 'Etaj 19'),
    (21, 'Etaj 20'),
    (22, 'Mansarda'),
    (23, 'Ultimele 2 etaje'),
]